
////
This file is generated! See scripts/generate_template.py --docs
////

[[exported-fields]]
== Exported Fields

    These are the fields exported by the logging system and available for searching
from Elasticsearch and Kibana.  Use the full, dotted field name when searching.
For example, for an Elasticsearch /_search URL, to look for a Kubernetes pod name,
use `/_search/q=kubernetes.pod_name:name-of-my-pod`
This document describes fields that may not be present in your logging store.
Not all of these fields are present in every record.
The fields are grouped in the following categories:

* <<exported-fields-Default>>
* <<exported-fields-kubernetes>>


'''
[[exported-fields-Default]]
=== [big]*Top Level Fields*

The top level fields are common to every application, and may be present in every record.
For the Elasticsearch template, this is what populates the actual mappings
of either the `\_default_` type (in ES 5.x or earlier) or the only single `_doc` type (in ES 6.x or later)
in the template's mapping section.

Read more about Elasticsearch index types deprecation:

- https://www.elastic.co/guide/en/elasticsearch/reference/6.0/default-mapping.html[Default mapping deprecation in ES 6.x]
- https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html[Removal of mappings types in ES 6.x]



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000+00:00

format: yyyy-MM-dd HH:mm:ss,SSSZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime

UTC value marking when the log payload was created, or when log payload was first collected if the creation time is not known;
this is the log processing pipeline’s “best effort” determination of when the log payload was generated
FYI: the “@” prefix convention to note a field as being reserved for a particular use; in this case, most tools by default look for “@timestamp” with ElasticSearch


==== hostname

type: keyword

FQDN of the entity generating the original payload.  This field is a best effort attempt to derive this context; sometimes the entity generating it knows it; other times that entity has a restricted namespace itself, and the collector or normalizer knows that.


==== ipaddr4

type: ip

IP address v4 of the source server. Can be an array.


==== ipaddr6

type: ip

IP address v6 of the source server (if available). Can be an array.


==== level

type: keyword

example: info

Logging level as provided by: rsyslog(severitytext property), python's
logging module, etc.
Possible values are as listed here: http://sourceware.org/git/?p=glibc.git;a=blob;f=misc/sys/syslog.h;h=ee01478c4b19a954426a96448577c5a76e6647c0;hb=HEAD#l74 plus `trace` and `unknown`
That is: alert crit debug emerg err info notice trace unknown warning
Note that `trace` isn't in the syslog.h list but many applications use it
`unknown` is only used when the logging system gets a value it doesn't understand
`unknown` is the highest level
`trace` should be considered as higher (more verbose) than `debug`
`error` should be converted to `err`
`panic` should be converted to `emerg`
`warn` should be converted to `warning`
Numeric values from syslog/journal PRIORITY can usually be mapped using the priority values as listed here:
http://sourceware.org/git/?p=glibc.git;a=blob;f=misc/sys/syslog.h;h=ee01478c4b19a954426a96448577c5a76e6647c0;hb=HEAD#l51
That is, 0 -> emerg, 1 -> alert, ..., 7 -> debug, 8 -> trace, 9 -> unknown
Log levels/priorities from other logging systems should be mapped to the nearest match
For example, from python logging: https://docs.python.org/2.7/library/logging.html#logging-levels
CRITICAL -> crit, ERROR -> err, ...., DEBUG -> debug


==== message

type: text

example: TODO

Typical log entry message, or payload, possibly stripped of metadata pulled out of it by collector/normalizer, UTF-8 encoded.


==== pid

type: keyword

This is the process ID of the logging entity, if available.


==== namespace_name

type: keyword

example: my-cool-project-in-lab04

format: [a-zA-Z][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]

Associate this record with the namespace with this name.
This value will not be stored.  It is only used to associate the
record with the appropriate namespace for access control and
visualization.  Normally this value will be given in the tag, but if the
protocol does not support sending a tag, this field can be used.
If this field is present, it will override the
namespace given in the tag or in kubernetes.namespace_name.
The format is the same format used for Kubernetes namespace names.
See also namespace_uuid.


==== namespace_uuid

type: keyword

example: 82f13a8e-882a-4344-b103-f0a6f30fd218

format: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}

The uuid associated with the namespace_name.
This value will not be stored.  It is only used to associate the
record with the appropriate namespace for access control and
visualization.  If this field is present, it will override the
uuid given in kubernetes.namespace_uuid.  This will also cause
the Kubernetes metadata lookup to be skipped for this log record.



'''
[[exported-fields-kubernetes]]
=== [big]*kubernetes Fields*

Namespace for kubernetes-specific metadata



==== kubernetes.pod_name

type: keyword

The name of the pod


==== kubernetes.pod_id

type: keyword

Kubernetes ID of the pod.


==== kubernetes.namespace_name

type: keyword

The name of the namespace in Kubernetes.


==== kubernetes.namespace_id

type: keyword

ID of the namespace in Kubernetes.


==== kubernetes.host

type: keyword

Kubernetes node name


==== kubernetes.container_name

type: text

The name of the container in Kubernetes.



'''
[[exported-fields-kubernetes.annotations]]
=== [big]*kubernetes.annotations Fields*

Annotations associated with the Kubernetes object



'''
[[exported-fields-kubernetes.labels]]
=== [big]*kubernetes.labels Fields*

Labels attached to the Kubernetes object Each label name is a subfield of labels field. Each label name is de-dotted: dots in the name are replaced with underscores.



==== kubernetes.labels.deployment

type: keyword

example: logging-kibana-3

The deployment associated with this Kubernetes object


==== kubernetes.labels.deploymentconfig

type: keyword

example: logging-kibana

The deploymentconfig associated with this Kubernetes object



'''
[[exported-fields-kubernetes.event]]
=== [big]*kubernetes.event Fields*

The kubernetes event obtained from kubernetes master API The event is already JSON object and as whole nested under kubernetes field This description should loosely follow 'type Event' in https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go



==== kubernetes.event.verb

type: keyword

example: ADDED

The type of event, can be ADDED, MODIFIED, DELETED



'''
[[exported-fields-kubernetes.event.metadata]]
=== [big]*kubernetes.event.metadata Fields*

Information related to the location and time of the event creation



==== kubernetes.event.metadata.name

type: keyword

example: java-mainclass-1.14d888a4cfc24890

Name of the object that triggered the event creation


==== kubernetes.event.metadata.namespace

type: keyword

example: default

The name of the namespace which induced the event It differs from namespace_name, which will be in case of every event the 'eventrouter'


==== kubernetes.event.metadata.selfLink

type: keyword

example: /api/v1/namespaces/javaj/events/java-mainclass-1.14d888a4cfc24890

Link to the event itself


==== kubernetes.event.metadata.uid

type: keyword

example: d828ac69-7b58-11e7-9cf5-5254002f560c

Event's unique ID


==== kubernetes.event.metadata.resourceVersion

type: integer

example: 311987

String that identifies the server's internal version of the event that can be used by clients to determine when objects have changed



'''
[[exported-fields-kubernetes.event.involvedObject]]
=== [big]*kubernetes.event.involvedObject Fields*

Description of the object involved in the event creation



==== kubernetes.event.involvedObject.kind

type: keyword

example: ReplicationController

Type of the object


==== kubernetes.event.involvedObject.namespace

type: keyword

example: default

The name of the namespace in which the object triggered the event In case this event is not triggered by a pod then it differs from kubernetes.namespace_name, which will be in case of every event eventrouter's namespace


==== kubernetes.event.involvedObject.name

type: keyword

example: java-mainclass-1

Name of the object that triggered the event


==== kubernetes.event.involvedObject.uid

type: keyword

example: e6bff941-76a8-11e7-8193-5254002f560c

Object's unique ID


==== kubernetes.event.involvedObject.apiVersion

type: keyword

example: v1

Version of kubernetes master API


==== kubernetes.event.involvedObject.resourceVersion

type: keyword

example: 308882

String that identifies the server's internal version of the pod triggering the event that can be used by clients to determine when objects have changed


==== kubernetes.event.reason

type: keyword

example: SuccessfulCreate

Short, machine understandable string that gives the reason for this event being generated


==== kubernetes.event.source_component

type: keyword

example: replication-controller

Component which reported this event


==== kubernetes.event.firstTimestamp

type: date

example: 2017-08-07 10:11:57+00:00

format: yyyy-MM-dd HH:mm:ss,SSSZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime

The time at which the event was first recorded


==== kubernetes.event.count

type: integer

example: 1

The number of times this event has occurred


==== kubernetes.event.type

type: keyword

example: Normal

Type of this event (Normal, Warning), new types could be added in the future


